services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  admin:
    build: ./admin
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata: